services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    container_name: easypark-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${_saPassword:?_saPassword is required}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - easypark-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: easypark-rabbitmq
    hostname: "rabbitmq"
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${_rabbitMqUser:?_rabbitMqUser is required}
      - RABBITMQ_DEFAULT_PASS=${_rabbitMqPassword:?_rabbitMqPassword is required}
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - 5672
      - 15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - easypark-network

  easypark-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - _connectionString=${_connectionString:?_connectionString is required}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - _corsOrigins=${_corsOrigins:?_corsOrigins is required}
      - _rabbitMqHost=${_rabbitMqHost:?_rabbitMqHost is required}
      - _rabbitMqUser=${_rabbitMqUser:?_rabbitMqUser is required}
      - _rabbitMqPassword=${_rabbitMqPassword:?_rabbitMqPassword is required}
      - _rabbitMqPort=${_rabbitMqPort:?_rabbitMqPort is required}
      - _stripe=${_stripe:?Stripe secret key is required}
      - _stripePublishableKey=${_stripePublishableKey:?_stripePublishableKey is required}
      - _stripePublishable=${_stripePublishable:?_stripePublishable is required}
      - _jwtKey=${_jwtKey:?_jwtKey is required}
      - _jwtIssuer=${_jwtIssuer:?_jwtIssuer is required}
      - _jwtAudience=${_jwtAudience:?_jwtAudience is required}
    ports:
      - "8080:8080"
    networks:
      - easypark-network
    depends_on:
      - sqlserver
      - rabbitmq

  easypark-subscriber:
    restart: on-failure
    build:
      context: .
      dockerfile: EasyPark.Subscriber/Dockerfile
    environment:
      - _connectionString=${_connectionString:?_connectionString is required}
      - _rabbitMqHost=${_rabbitMqHost:?_rabbitMqHost is required}
      - _rabbitMqUser=${_rabbitMqUser:?_rabbitMqUser is required}
      - _rabbitMqPassword=${_rabbitMqPassword:?_rabbitMqPassword is required}
      - _rabbitMqPort=${_rabbitMqPort:?_rabbitMqPort is required}
      - _fromAddress=${_fromAddress:?_fromAddress is required}
      - _password=${_password:?_password is required}
      - _host=${_host:?_host is required}
      - _enableSSL=${_enableSSL:?_enableSSL is required}
      - _displayName=${_displayName:?_displayName is required}
      - _timeout=${_timeout:?_timeout is required}
      - _port=${_port:?_port is required}
    networks:
      - easypark-network
    depends_on:
      - rabbitmq
      - sqlserver

volumes:
  sqlserver_data:

networks:
  easypark-network:
    driver: bridge
